name: Stop py-youwol
description: Stop py-youwol and collect logs into an artifact
author: jdecharne@youwol.com


inputs:

  instance:
    description: >
      An abstract string value, as output by youwol/nestor/py-youwol/start action, i.e :
      - uses: youwol/nestor/py-youwol/start@v1
        id: start_py-youwol
        with:
          repository_conf: youwol/integration-tests-conf
          ref_conf: main
          path_conf: yw_config_IT.py
      - uses: youwol/nestor/py-youwol/stop@v1
        id: stop_py-youwol
        with:
          instance: steps.start_py-youwol.outputs.instance
    required: true

  artifact:
    description: >
      Name of the artifact to upload.
      Default to py-youwol_logs
    default: py-youwol_logs


runs:
  using: composite

  steps:
    - name: Stop py-youwol
      id: stop_py-youwol
      working-directory: ${{ inputs.instance }}
      run: |
        # stop py-youwol coverage
        echo "::group::run shutdown script"
        sh py-youwol.shutdown.sh
        echo "::endgroup::"
        #
        echo "::group::generate coverage HTML report"
        COVERAGE_DEBUG_FILE=coverage_html.debug coverage html
        echo "::endgroup::"
      shell: sh

    - name: Upload artifacts
      id: upload_artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ${{ inputs.artifact }}
        path: ${{ inputs.instance }}
