name: Tear Down PyYouwol Integration Testing
description: Stop daemonized py-youwol and remove directory
inputs:
  src_dir:
    description: "Path to py-youwol sources directory"
    required: true
  conf_dir:
    description: "Path to configuration directory"
    required: true
  work_dir:
    description: "Path to work directory"
    required: true

runs:
  using: 'composite'

  steps:
    - name: Stop py-youwol
      id: stop_py-youwol
      uses: youwol/nestor/py/stop_py-youwol@main
      with:
        src_dir: ${{ inputs.src_dir }}
        work_dir: ${{ inputs.work_dir }}
        archive: integration_py-youwol_work_dir

    - name: Tear down configuration
      id: tear_down_py_youwol_conf
      env:
        conf_dir: ${{ inputs.conf_dir }}
      run: |
        ### Tear down py-youwol
        rm -r ${conf_dir}
      shell: sh

    - name: Summary
      id: sunnary
      run: |
        ### Log summary
        message="py-youwol has been shutdown and afferent directories have been removed"
        echo "::notice title=Py-Youwol Integration Testing::${message}"
      shell: bash
