name: Prepare Python Repository
description: Prepare Python repository, optionally moving it to path outside workspace
author: jdecharne@youwol.com


inputs:

  token:
    description: >
      Personal access token (PAT) for checkout
      Default to the workflow token
    default: ${{ github.token }}

  repository:
    description: >
      Repository name with owner.
      Default to the repository of the workflow
    default: ${{ github.repository }}

  ref:
    description: >
      Branch, tag or SHA to checkout. 
      Default to the reference that triggered the workflow
    default: ${{ github.ref }}

  python-version:
    description: >
      Python version to use.
      Default to 3.12
    default: '3.12'

  path:
    description: "The final path of the local repository. Default to empty : the repository will not be moved once checkout"
    default: ''

runs:
  using: composite

  steps:
    - name: Setup Action
      id: setup_action
      run: |
        # Setup Action parameters
        repo_string="${{ inputs.repository }}@${{ inputs.ref }}"
        echo "repoString=$repo_string" >> $GITHUB_OUTPUT
        if [ -n "${{ inputs.path }}" ]; then
          random=$(awk 'BEGIN { srand(); print int(rand()*32768) }' /dev/null | base64)
          checkout_path=".py_prepare_${random}"
          echo "checkoutPath=${checkout_path}" >> $GITHUB_OUTPUT 
        fi
      shell: sh

    - name: Checkout repository
      id: checkout
      uses: actions/checkout@v3
      with:
        repository: ${{ inputs.repository }}
        token: ${{ inputs.token }}
        ref: ${{ inputs.ref }}
        path: ${{ steps.setup_action.outputs.checkoutPath }}

    - name: Setup Python
      id: setup_python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}
        cache: 'pip'
        cache-dependency-path: ${{ steps.setup_action.outputs.checkoutPath }}/pyproject.toml

    - name: Install py-youwol
      id: install_py-youwol
      working-directory: ${{ steps.setup_action.outputs.checkoutPath }}
      run: pip install .[qa]
      shell: sh

    - name: Move repository
      id: move
      if: inputs.path != ''
      run: mv '${{ steps.setup_action.outputs.checkoutPath }}' '${{ inputs.path }}'
      shell: sh

    - name: Update Environment
      id: update_env
      env:
        INPUT_PATH: ${{ inputs.path }}
      run: |
        echo "PY_YOUWOL_SOURCES=${INPUT_PATH:-$GITHUB_WORKSPACE}" >> "$GITHUB_ENV"
        echo "PY_YOUWOL_BIN=$(which youwol)" >> "$GITHUB_ENV"
        echo "PY_YOUWOL_BIN_COVERAGE=$(which coverage)" >> "$GITHUB_ENV"
      shell: sh
