name: Set up PyYouwol Integration Testing
description: Set up & launch py-youwol for integration testing
inputs:
  src_ref:
    description: Git ref for py-youwol checkout
    required: false
    default: main
  conf_ref:
    description: Git ref for integration-tests-conf checkout
    required: false
    default: main
  token:
    description: Github Token for checkout
    required: true
outputs:
  src_dir:
    description: path to py-youwol source directory
    value: ${{ steps.summary.outputs.src_dir }}
  conf_dir:
    description: path to configuration directory
    value: ${{ steps.summary.outputs.conf_dir }}
  work_dir:
    description: path to working directory
    value: ${{ steps.summary.outputs.work_dir }}

runs:
  using: 'composite'
  steps:
    - name: Set up action variables
      id: set_up_vars
      run: |
        ### Set up action variables
        random=$(awk 'BEGIN { srand(); print int(rand()*32768) }' /dev/null | base64)
        conf_dir="$GITHUB_WORKSPACE/.py-youwol-integration_conf/${random}"
        echo "conf_dir=${conf_dir}" >> $GITHUB_OUTPUT
      shell: sh

###### Checkout repositories
    # Checkout the integration testing conf into $py_it_conf_dir, using the ref from input integrationTestsRef
    - name: Checkout integration tests configuration repo
      id: checkout_it_conf
      uses: actions/checkout@v3
      with:
        repository: youwol/integration-tests-conf
        ref: ${{ inputs.conf_ref }}
        path: ${{ steps.set_up_vars.outputs.conf_dir }}
        token: ${{ inputs.token }}
    # Checkout py-youwol into $py_it_src_dir, using the ref from input pyYouwolRef
    - name: Start py-youwol
      id: start_py-youwol
      uses: youwol-jdecharne/nestor/py/start_py-youwol@main
      with:
        ref: ${{ inputs.src_ref }}
        config: ${{ steps.set_up_vars.outputs.conf_dir }}/yw_config_IT.py
        token: ${{ inputs.token }}

    # Finally, some annotated logging about how everything is configured
    - name: Summary
      id: summary
      env:
        src_ref: ${{ inputs.scr_ref }}
        conf_ref: ${{ inputs.conf_ref }}
        src_dir: ${{ steps.start_py-youwol.outputs.src_dir }}
        conf_dir: ${{ steps.set_up_vars.outputs.conf_dir }}
        work_dir: ${{ steps.start_py-youwol.outputs.work_dir }}
      run: |
        ### Log summary
        echo "::notice title=Py-Youwol Integration Testing::youwol/py-youwol@${src_ref} running with configuration from youwol/integration-tests-conf@${conf_ref}"
        echo "src_dir=${src_dir}" >> $GITHUB_OUTPUT
        echo "conf_dir=${conf_dir}" >> $GITHUB_OUTPUT
        echo "work_dir=${work_dir}" >> $GITHUB_OUTPUT
      shell: sh
