name: Set up a typescript package repository
description: Set up a repository and install package.json with yarn
inputs:
  ref:
    description: "the ref to checkout (default to develop)"
    required: false
    default: develop
  path:
    description: "the path where to checkout"
    required: false
    default: ''
  repository:
    description: "the repository to checkout"
    required: false
    default: ''
  token:
    description: "the github token for actions/checkout"
    required: true

outputs:
  name:
    description: "the name of the project"
    value: ${{ steps.summary.outputs.name }}
  version:
    description: "the version of the project"
    value: ${{ steps.summary.outputs.version }}

runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      id: checkout
      uses: actions/checkout@v3
      with:
        token: ${{ inputs.token }}
        ref: ${{ inputs.ref }}
        path: ${{ inputs.path }}
        repository: ${{ inputs.repository }}

    - name: Setup Node.js
      id: setup_node
      uses: actions/setup-node@v2
      with:
        node-version: '16'
        cache: 'yarn'

    - name: Install dependencies
      id: install_yarn_deps
      working-directory: ${{ inputs.path }}
      run: yarn --frozen-lockfile
      shell: bash

    - name: Summary
      id: summary
      env:
        job_id: ${{ github.job }}
      run: |
        ### Log summary & set action outputs
        name=$(jq -r -e ".name" package.json)
        version=$(jq -r -e ".version" package.json)
        echo "::set-output name=name::${name}"
        echo "::set-output name=version::${version}"
        echo "::notice title=Set up repository for job '${job_id}'::Project '${name}', version '${version}'"
      shell: bash
