name: Run Typescript Tests with coverage
description: Run Typescript tests with coverage
author: jdecharne@youwol.com


inputs:

  path:
    description: >
      The path of the Typescript repository where to execute tests.
      Default to empty : tests will executed into the workflow workspace
    default: ''

  artifacts_suffix:
    description: >
      A suffix appended to the artifacts produced.
      Default to this action name prefixed with an underscore.
    default: _${{ github.action }}

  token:
    description: >
      Personal access token (PAT) for checkout of configuration and py-youwol repositories.
      Only make sense if such one or both of these repositories is checkout, ignored otherwise.
      Default to the workflow token
    default: ${{ github.token }}

  py-youwol_conf_path:
    description: >
      Path to the configuration file to use, for py-youwol integration.
      Either relative to conf_repository, or to workflow workspace if no py-youwol-conf-repository.
      Default to empty, meaning that no py-youwol integration is done
    default: ''

  py-youwol_path:
    description: >
      The path of the local py-youwol repository.
      Only make sense if py-youwol-conf-path is set.
      Default to empty : py-youwol repository will be checkout if py-youwol-conf-path is set.
    default: ''

  py-youwol_ref:
    description: >
      Branch, tag or SHA to checkout py-youwol repository. 
      Only make sense if py-youwol-path is not configured and py-youwol-conf-path is set, ignored otherwise.
      Default to 'main'
    default: main

  py-youwol_conf_repository:
    description: >
      Repository name with owner for the configuration.
      Only make sense if py-youwol-conf-path is set, otherwise ignored.
      Default to empty : the configuration is taken from workflow workspace
    default: ''

  py-youwol_conf_ref:
    description: >
      Branch, tag or SHA to checkout the configuration repository. 
      Only make sense if such a repository is configured, ignored otherwise
      Default to 'main'
    default: main

outputs:

  result:
    description: Result of the tests
    value: ${{ steps.tests_coverage.outputs.result }}


runs:
  using: composite

  steps:
    - name: Start py-youwol
      id: start_py-youwol
      if: inputs.py-youwol_conf_path
      uses: youwol/nestor/py-youwol/start@test
      with:
          token: ${{ inputs.token }}
          path: ${{ inputs.py-youwol_path }}
          ref: ${{ inputs.py-youwol_ref }}
          conf_repository: ${{ inputs.py-youwol_conf_repository }}
          conf_ref: ${{ inputs.py-youwol_conf_ref }}
          conf_path: ${{ inputs.py-youwol_conf_path }}

    - name: Tests with coverage
      id: tests_coverage
      working-directory: ${{ inputs.path }}
      run: yarn -s test-coverage --reporters=github-actions || echo "result=failure" >> $GITHUB_OUTPUT
      shell: sh

    - name: Stop py-youwol
      id: stop_py-youwol
      if: inputs.py-youwol_conf_path
      uses: youwol/nestor/py-youwol/stop@test
      with:
        instance: ${{ steps.start_py-youwol.outputs.instance }}
        artifact: py-youwol_log_${{ inputs.artifacts_suffix }}
