name: Typescript Static Analysis
description: Run static analysis on a typescript project
author: jdecharne@youwol.com
inputs:
  skip:
    required: false
    description: |
      list of steps to skip : audit, eslint, prettier
    default: ''
  acceptedGhsaIds:
    required: false
    description: |
      list of ghsaId to accept (they will still generated a warning)
    default: ''
runs:
  using: node16
  main: 'dist/action/index.js'
