name: Static analyzes a Typescript repository
description: Various quality checks for Typescript packages
author: jdecharne@youwol.com

runs:
  using: composite

  steps:
    - name: Audit dependencies
      id: yarn_audit
      run: yarn audit
      shell: sh

    - name: Check code quality with yarn eslint
      id: yarn_eslint
      run: yarn eslint
      shell: sh

    - name: Check code formatting with yarn prettier
      id: yarn_prettier
      continue-on-error: true
      run: yarn prettier --check .
      shell: sh

    - name: Prettier failure details
      id: yarn_prettier_failure_details
      if: steps.yarn_prettier.outcome == 'failure'
      run: |
        # Yarn prettier --list-different
        echo "::group::Yarn prettier logs"
        files=$(yarn -s prettier --list-different .) && echo $files
        echo "::endgroup::"
        title="Malformatted code source"
        echo "::error title=${title}::See annotations or job logs for details"
        for file in ${files} ; do
          echo "::error file=${file},title=${title}::Mal-formatted file"
        done
        exit 1
      shell: sh
