name: Static analyzes a Typescript repository
description: Various quality checks for Typescript packages
author: jdecharne@youwol.com

runs:
  using: composite

  steps:
    - name: Audit dependencies
      id: yarn_audit
      run: yarn audit
      shell: sh

    - name: Check code quality with yarn eslint
      id: yarn_eslint
      run: yarn eslint
      shell: sh

    - name: Check code formatting with yarn prettier
      id: yarn_prettier
      run: |
        # Yarn prettier
        echo "::group::Yarn prettier logs"
        if files=$(yarn -s prettier --list-different .) ; then
          echo "::endgroup::"
          echo "result=ok" >> $GITHUB_ACTION
        else
          echo $files
          echo "::endgroup::"
          title="Malformatted code source for job '${job_id}'"
          echo "::warning title=${title}::See 'Yarn prettier logs' and/or annotations for details"
          for file in ${files} ; do
            echo "::warning file=${file},title=${title}::Mal-formatted file"
          done
          echo "result=ko" >> $GITHUB_ACTION
        fi
      shell: sh
