name: Start py-youwol
description: Start py-youwol and output an abstract string instance
author: jdecharne@youwol.com


inputs:

  token:
    description: >
      Personal access token (PAT) for checkout of configuration and py-youwol repositories.
      Only make sense if such one or both of these repositories is checkout, ignored otherwise.
      Default to the workflow token
    default: ${{ github.token }}

  conf_repository:
    description: >
      Repository name with owner for the configuration.
      Default to empty : the configuration is taken from workflow workspace
    default: ''

  conf_ref:
    description: >
      Branch, tag or SHA to checkout the configuration repository. 
      Only make sense if such a repository is configured, ignored otherwise
      Default to 'main'
    default: main

  conf_path:
    description: >
      Path to the configuration file to use.
      Either relative to conf_repository, or to workflow workspace if no conf_repository
    required: true

  ref:
    description: >
      Branch, tag or SHA to checkout py-youwol repository. 
      Only make sense if path is not configured, ignored otherwise.
      Default to 'main'
    default: main

  path:
    description: >
      The path of the local py-youwol repository.
      Default to empty : py-youwol repository will be checkout.
    default: ''

outputs:
  instance:
    description: >
      An abstract string value, for youwol/nestor/py-youwol/stop action, i.e :
      - uses: youwol/nestor/py-youwol/start@v1
        id: start_py-youwol
        with:
          conf_repository: youwol/integration-tests-conf
          conf_path: yw_config_IT.py
      - uses: youwol/nestor/py-youwol/stop@v1
        id: stop_py-youwol
        with:
          instance: steps.start_py-youwol.outputs.instance
    value: ${{ steps.setup_action.outputs.instance }}


runs:
  using: composite

  steps:
    - name: Set Up Action
      id: setup_action
      env:
        INPUTS_CONF_REPOSITORY: ${{ inputs.conf_repository }}
        INPUTS_CONF_PATH: ${{ inputs.conf_path }}
        INPUTS_PATH: ${{ inputs.path }}
      run: ${{ github.action_path }}/setup_action.sh
      shell: sh

    - name: Prepare py-youwol repository
      id: prepare_py-youwol
      if: steps.setup_action.outputs.py-youwol-checkout
      uses: youwol/nestor/py/prepare@v1
      with:
        repository: youwol/py-youwol
        ref: ${{ inputs.ref }}
        requirements: dev-requirements.txt
        path: ${{ steps.setup_action.outputs.sources }}

    - name: Checkout configuration repository
      id: checkout_conf
      if: inputs.conf_repository != ''
      uses: actions/checkout@v3
      with:
        token: ${{ inputs.token }}
        repository: ${{ inputs.conf_repository }}
        ref: ${{ inputs.conf_ref }}
        path: ${{ steps.setup_action.outputs.conf-checkout-path }}

    - name: Move configuration
      id: move_-conf
      if: inputs.conf_repository != ''
      run: mv ${{ steps.setup_action.outputs.conf-checkout-path }} ${{ steps.setup_action.outputs.conf-directory }}
      shell: sh

    - name: Start py-youwol
      id: start_py-youwol
      working-directory: ${{ steps.setup_action.outputs.instance }}
      env:
        PYTHONPATH: ${{ steps.setup_action.outputs.sources }}
        COVERAGE_DEBUG_FILE: coverage.coverage
        PY_YOUWOL_MAIN_SCRIPT: ${{ steps.setup_action.outputs.sources }}/youwol/main.py
        PY_YOUWOL_CONFIG: ${{ steps.setup_action.outputs.config }}
      run: coverage run "$PY_YOUWOL_MAIN_SCRIPT" --conf "$PY_YOUWOL_CONFIG" --daemonize
      shell: sh

    - name: Wait for py-youwol readiness
      id: wait_py-youwol
      run: ${{ github.action_path }}/wait_py-youwol.sh
      shell: sh
