name: Start PyYouwol
description: Set up & launch py-youwol
inputs:
  ref:
    description: Git ref for py-youwol checkout
    required: false
    default: master
  config:
    description: Path to a py-youwol config file
    required: true
  token:
    description: Github Token for checkout
    required: true
outputs:
  src_dir:
    description: path to py-youwol source directory
    value: ${{ steps.summary.outputs.src_dir }}
  work_dir:
    description: path to working directory
    value: ${{ steps.summary.outputs.work_dir }}

runs:
  using: 'composite'
  steps:
    - name: Set up action variables
      id: set_up_vars
      run: |
        ### Set up action variables
        echo "::group::make working directory"
        random=$(awk 'BEGIN { srand(); print int(rand()*32768) }' /dev/null | base64)
        work_dir="${RUNNER_TEMP}/start_py-youwoul/${random}"
        mkdir -p "${work_dir}"
        echo "::endgroup::"
        #
        echo "::group::outputs"
        echo "::set-output name=work_dir::${work_dir}"
        echo "::set-output name=src_dir::$GITHUB_WORKSPACE/.start_py-youwol/${random}"
        echo "::set-output name=shutdown_script::${work_dir}/py-youwol.shutdown.sh" 
        echo "::endgroup::"
      shell: sh

###### Checkout repositories
    # Checkout py-youwol into $py_it_src_dir, using the ref from input pyYouwolRef
    - name: Set up py-youwol repository
      id: setup_py_youwol
      uses: youwol/nestor/py/set_up_repo@main
      with:
        repository: youwol/py-youwol
        ref: ${{ inputs.ref }}
        path: ${{ steps.set_up_vars.outputs.src_dir }}
        token: ${{ inputs.token }}

###### Launch py-youwol
    # Launching py-youwol
    # The working directory is important, it's there that the shutdown script will be generated
    # PYTHONPATH is defined only for this step, so it does not pollute other steps or jobs
    - name: Launch py-youwol
      id: launch_py_youwol
      working-directory: ${{ steps.set_up_vars.outputs.work_dir }}
      env:
        PYTHONPATH: ${{ steps.set_up_vars.outputs.src_dir }}
        main_path: ${{ steps.set_up_vars.outputs.src_dir }}/youwol/main.py
        config_path: ${{ inputs.config }}
      run: python3 -u ${main_path} --conf ${config_path} > py-youwol.out 2> py-youwol.err &
      shell: sh
    # Try at most 10 times to call healtz endpoint, checking its response, and waiting 1 second between retries
    - name: Wait for running instance
      id: wait_py_youwol_running
      run: |
        ### Wait for running instance
        jq_cmd='if .status == "py-youwol ok" then halt else error ("incorrect status from py-youwol") end'
        #
        echo "::group::Trying at most 10 times to call healtz endpoint, waiting 1 seconde between retries"
        for try in $(seq 1 1 10); do
          echo "try $try/10 to contact py-youwol instance"
          response=$(curl --silent http://localhost:2001/healthz || echo "No response")
          echo "Response : '${response}'"
          if echo "${response}" | jq -e "${jq_cmd}"; then
            exit 0
          else
            echo "Invalid response. Retrying in 1 second"
            sleep 1
          fi
        done
        #
        echo "::endgroup::"
        echo "::error ::Failed to contact py-youwol instance after 10 seconds"
        exit 1
      shell: sh
    # Finally, some annotated logging about how everything is configured
    - name: Summary
      id: summary
      env:
        src_ref: ${{ inputs.ref }}
        config: ${{ inputs.config }}
        src_dir: ${{ steps.set_up_vars.outputs.src_dir }}
        work_dir: ${{ steps.set_up_vars.outputs.work_dir }}
      run: |
        ### Log summary
        echo "::notice title=Start Py-Youwol::youwol/py-youwol@${src_ref} running with config ${config}"
        echo "::set-output name=src_dir::${src_dir}"
        echo "::set-output name=work_dir::${work_dir}"
      shell: sh
