name: Prepare Python Repository
description: Prepare Python repository, optionally moving it to path outside workspace
author: jdecharne@youwol.com


inputs:

  token:
    description: >
      Personal access token (PAT) for checkout
      Default to the workflow token
    default: ${{ github.token }}

  repository:
    description: >
      Repository name with owner.
      Default to the repository of the workflow
    default: ${{ github.repository }}

  ref:
    description: >
      Branch, tag or SHA to checkout. 
      Default to the reference that triggered the workflow
    default: ${{ github.ref }}

  requirements:
    description: >
      Path, relative to repository, of the requirements.txt file.
      Default to requirements.txt
    default: 'requirements.txt'

  path:
    description: "The final path of the local repository. Default to empty : the repository will not be moved once checkout"
    default: ''

runs:
  using: composite

  steps:
    - name: Setup Action
      id: setup_action
      run: |
        # Setup Action parameters
        repo_string="${{ inputs.repository }}@${{ inputs.ref }}"
        echo "repoString=$repo_string" >> $GITHUB_OUTPUT
        if [ -n "${{ inputs.path }}" ]; then
          random=$(awk 'BEGIN { srand(); print int(rand()*32768) }' /dev/null | base64)
          checkout_path=".py_prepare_${random}"
          echo "::notice title=$repo_string::Preparing $repo_string in ${{ inputs.path }}"
          echo "checkoutPath=${checkout_path}" >> $GITHUB_OUTPUT 
          echo "requirementsPath=${checkout_path}/${{ inputs.requirements }}" >> $GITHUB_OUTPUT
        else
          echo "requirementsPath=${{ inputs.requirements }}" >> $GITHUB_OUTPUT
        fi
      shell: sh

    - name: Checkout repository
      id: checkout
      uses: actions/checkout@v3
      with:
        repository: ${{ inputs.repository }}
        token: ${{ inputs.token }}
        ref: ${{ inputs.ref }}
        path: ${{ steps.setup_action.outputs.checkoutPath }}

    - name: Setup Python 3.9
      id: setup_python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        cache: 'pip'
        cache-dependency-path: ${{ steps.setup_action.outputs.requirementsPath }}

    - name: Install py-youwol dependencies
      id: install_py-youwol_dep
      working-directory: ${{ steps.setup_action.outputs.checkoutPath }}
      run: |
        # pip install -r ${{ inputs.requirements }}
        echo "::group::pip output"
        pip install -r ${{ inputs.requirements }}
        echo "::endgroup::"
      shell: sh

    - name: Move repository
      id: move
      if: inputs.path != ''
      run: |
        # mv ${{ steps.setup_action.outputs.checkoutPath }} ${{ inputs.path }}
        mv ${{ steps.setup_action.outputs.checkoutPath }} ${{ inputs.path }}
      shell: sh
