name: Stop PyYouwol
description: Stop daemonized py-youwol and remove directory
inputs:
  src_dir:
    description: Path to py-youwol sources directory
    required: true
  work_dir:
    description: Path to work directory
    required: true
  archive:
    description: work directory (i.e. logs) archive
    required: false
    default: py-youwol_work_dir

runs:
  using: 'composite'

  steps:
    - name: Stop py-youwol
      id: stop_py-youwol
      env:
        shutdown_script: ${{ inputs.work_dir }}/py-youwol.shutdown.sh
      run: |
        if [ -e ${shutdown_script} ] ; then
          sh ${shutdown_script}
        else
          echo "ERROR : SCRIPT NOT FOUND at ${shutdown_script}"
        fi
      shell: sh

    - name: Upload py-youwol work directory
      uses: actions/upload-artifact@v3
      if: ${{ inputs.archive }}
      with:
        name: ${{ inputs.archive }}
        path: ${{ inputs.work_dir }}

    - name: Tear down
      id: tear_down_py_youwol
      env:
        src_dir: ${{ inputs.src_dir }}
        work_dir: ${{ inputs.work_dir }}
      run: |
        ### Tear down py-youwol
        rm -r ${src_dir}
        rm -r ${work_dir}
      shell: sh

    - name: Summary
      id: sunnary
      run: |
        ### Log summary
        message="py-youwol has been shutdown and afferent directories have been removed"
        echo "::notice title=Stop Py-Youwol::${message}"
      shell: bash
