name: Integration Tests

on:
  workflow_call:
    inputs:
      name:
        type: string
        description: |
          A name for these tests
        required: false
        default: 'py-youwol'
      pyYouwolRef:
        type: string
        description: |
          Ref (tag, branch or commit) of py-youwol to checkout
        required: false
      pyYouwolCoverage:
        type: boolean
        description: |
          Run coverage of py-youwol
        required: false
        default: false
      tsRepository:
        type: string
        description: |
          Repository to checkout
        required: false
      tsRef:
        type: string
        description: |
          Ref (tag, branch or commit) of the typescript repository to checkout
        required: false
      coverageOmit:
        type: string
        description: |
          Patterns of source path to omit from coverage, separated by comma
        required: false
    secrets:
      USERNAME_INTEGRATION_TESTS:
        required: true
      PASSWORD_INTEGRATION_TESTS:
        required: true
      USERNAME_INTEGRATION_TESTS_BIS:
        required: true
      PASSWORD_INTEGRATION_TESTS_BIS:
        required: true




jobs:
  integration_tests:
    name: Integration Tests
    runs-on: ubuntu-22.04
    steps:
      - name: Prepare py-youwol repository
        id: prepare_py-youwol
        uses: youwol/nestor/py-youwol/prepare@v3
        with:
          repository: youwol/py-youwol
          ref: ${{ inputs.pyYouwolRef }}
          path: ${{ runner.temp }}/py-youwol

      - name: Prepare Typescript repository
        id: prepare_ts
        uses: youwol/nestor/ts/prepare@v3
        with:
          repository: ${{ inputs.tsRepository }}
          ref: ${{ inputs.tsRef }}
          path: ${{ runner.temp }}/ts

      - name: Run py-youwol
        id: run_py-youwol
        uses: youwol/nestor/py-youwol/run@v3
        env:
          USERNAME_INTEGRATION_TESTS: ${{ secrets.USERNAME_INTEGRATION_TESTS }}
          PASSWORD_INTEGRATION_TESTS: ${{ secrets.PASSWORD_INTEGRATION_TESTS }}
          USERNAME_INTEGRATION_TESTS_BIS: ${{ secrets.USERNAME_INTEGRATION_TESTS_BIS }}
          PASSWORD_INTEGRATION_TESTS_BIS: ${{ secrets.PASSWORD_INTEGRATION_TESTS_BIS }}
        with:
          coverage: ${{ inputs.pyYouwolCoverage }}
          coverageOmit: ${{ inputs.coverageOmit }}
          name: ${{ inputs.name }}

      - name: Run tests
        id: run_tests
        uses: youwol/nestor/ts/tests@v3
