name: Continuous Integration

on:
  workflow_call:
    inputs:
      skip:
        type: string
        description: |
          List of checks to skip, among audit, eslint, prettier, autogen, build, doc, test, cleanness
        default: ''
        required: false
      pipeline:
        type: boolean
        description: |
          Use py-youwol pipeline
        default: true
        required: false

jobs:
  static_analysis:
    name: Static analysis
    runs-on: ubuntu-latest
    steps:
      - name: Prepare repository
        id: prepare
        uses: youwol/nestor/ts/prepare@v1

      - name: Static Analysis
        id: static_analysis
        uses: youwol/nestor/ts/static_analysis@v1
        with:
          skip: ${{ inputs.skip }}

      - name: On Static Analysis Failure
        id: static_analysis_failure
        if: steps.static_analysis.outputs.result == 'failure'
        uses: actions/github-script@v6
        with:
          script: core.setFailed("Job failed because static analysis has failed, see job logs and annotations.")

  build:
    name: Build & Tests
    runs-on: ubuntu-latest
    steps:
      - name: Warn about skipping autogen
        id: warn_skip_autogen
        if: contains(inputs.skip, 'autogen')
        run: echo "::warning title=Build & Test::Job parametrized to skip yarn auto-gen."
        shell: sh

      - name: Warn about skipping build
        id: warn_skip_build
        if: contains(inputs.skip, 'build')
        run: echo "::warning title=Build & Test::Job parametrized to skip yarn build."
        shell: sh

      - name: Warn about skipping doc
        id: warn_skip_doc
        if: contains(inputs.skip, 'doc')
        run: echo "::warning title=Build & Test::Job parametrized to skip yarn doc."
        shell: sh

      - name: Warn about skipping test
        id: warn_skip_test
        if: contains(inputs.skip, 'test')
        run: echo "::warning title=Build & Test::Job parametrized to skip yarn test."
        shell: sh

      - name: Warn about skipping git cleanness check
        id: warn_skip_git_cleanness
        if: contains(inputs.skip, 'cleanness')
        run: echo "::warning title=Build & Test::Job parametrized to skip git cleanness check."
        shell: sh

      - name: Prepare repository
        id: prepare
        uses: youwol/nestor/ts/prepare@v1

      - name: Prepare py-youwol repository
        if: inputs.pipeline
        id: prepare_py-youwol
        uses: youwol/nestor/py/prepare@v1
        with:
          repository: youwol/py-youwol
          ref: main
          path: ${{ runner.temp }}/py-youwol

      - name: Py-youwol templating
        if: "inputs.pipeline && ! contains(inputs.skip, 'autogen')"
        id: autogen
        env:
          PYTHONPATH: ${{ runner.temp }}/py-youwol
        run: yarn auto-gen || echo "result=failure" >> $GITHUB_OUTPUT
        shell: sh

      - name: Build
        if: "! contains(inputs.skip, 'build')"
        id: build
        run: yarn build || echo "result=failure" >> $GITHUB_OUTPUT
        shell: sh

      - name: Documentation
        if: "! contains(inputs.skip, 'doc')"
        id: doc
        run: yarn doc || echo "result=failure" >> $GITHUB_OUTPUT
        shell: sh

      - name: Test
        if: "! contains(inputs.skip, 'test')"
        id: test
        run: yarn test || echo "result=failure" >> $GITHUB_OUTPUT
        shell: sh

      - name: Check repository cleanness
        if: "! contains(inputs.skip, 'cleanness')"
        id: git_cleanness
        run: |
          git_status=$(git status -s)
          [ -z "$git_status" ] || ( echo "$git_status" ; echo "result=failure" >> $GITHUB_OUTPUT )
        shell: sh

      - name: On Py-youwol templating Failure
        id: autogen_failure
        if: steps.autogen.outputs.result == 'failure'
        uses: actions/github-script@v6
        with:
          script: core.setFailed("Job failed because py-youwol templating failed, see job logs and annotations.")

      - name: On Build Failure
        id: build_failure
        if: steps.build.outputs.result == 'failure'
        uses: actions/github-script@v6
        with:
          script: core.setFailed("Job failed because build failed, see job logs and annotations.")

      - name: On Documentation Failure
        id: doc_failure
        if: steps.doc.outputs.result == 'failure'
        uses: actions/github-script@v6
        with:
          script: core.setFailed("Job failed because documentation generation failed, see job logs and annotations.")

      - name: On Test Failure
        id: test_failure
        if: steps.test.outputs.result == 'failure'
        uses: actions/github-script@v6
        with:
          script: core.setFailed("Job failed because some tests failed, see job logs and annotations.")

      - name: On Repository dirty
        id: git_cleanness_dirty
        if: steps.git_cleanness.outputs.result == 'failure'
        uses: actions/github-script@v6
        with:
          script: core.setFailed("Job failed because some files were modified or untracked, see job logs and annotations.")
